version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - C:/Users/Barna/Projects/minocarto/db/mongod:/data/db
    ports:
      - 27019:27017
    restart: unless-stopped